server:
  port: 8080

spring:
  application:
    name: reasonAIble
  profiles:
    active: local
  #    default: local

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

anthropic:
  key: ${ANTHROPIC_API_KEY}
  base-url: ${ANTHROPIC_API_BASE_URL}
  version: ${ANTHROPIC_API_VERSION}
  model: ${ANTHROPIC_API_MODEL}
  timeout: 60
  max-tokens: 150
  temperature: 0.5
#  timeout: ${ANTHROPIC_API_TIMEOUT}
#  max-tokens: ${ANTHROPIC_API_MAX_TOKENS}
#  temperature: ${ANTHROPIC_API_TEMPERATURE}

knl:
  key: ${KNL_API_KEY}
  base-url: ${KNL_API_BASE_URL}
  model: ${KNL_API_MODEL}
  timeout: 60
  max-tokens: 150
  temperature: 0.5

management:
  endpoints:
    web:
      exposure:
        include: "*"

client:
  url: ${CLIENT_URL}
  url2: ${CLIENT_URL2}

jwt:
  secretKey: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXP_TIME}
    header: ${JWT_ACCESS_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_EXP_TIME}
    header: ${JWT_REFRESH_HEADER}
