server:
  port: 8080

spring:
  application:
    name: reasonAIble
  profiles:
#    activate: local
    default: local

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
