server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  cloud:
    vault:
      enabled: false

logging:
  level:
    com.example.boilerplate: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui
