global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    honor_labels: true
    basic_auth:
      username: prometheus@example.com
      password: prometheus
    static_configs:
      - targets: [ 'reasonaible:8080' ]
        labels:
          environment: 'dev'
          application: 'reasonaible'
