name: Java CI with Gradle

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    #    env:
    #      MYSQL_URL: jdbc:mysql://localhost:3306/actions-db?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    #      MYSQL_USER: root
    #      MYSQL_PASSWORD: root123!!!
    name: Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123!!!
          MYSQL_URL: jdbc:mysql://localhost:3306/actions-db
          #          MYSQL_DATABASE: actions-db
          MYSQL_USER: user
          MYSQL_PASSWORD: user123!!!
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Docker image build
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.APP }} .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dockerhub push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.APP }}:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker rm -f ${{ secrets.APP }}
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.APP }}:latest
            docker run -d -e VAULT_URI=${{ secrets.VAULT_URI }}  -e VAULT_TOKEN=${{ secrets.VAULT_TOKEN }} -e VAULT_AUTHENTICATION=${{ secrets.VAULT_AUTHENTICATION }} -e VAULT_BACKEND=${{ secrets.VAULT_BACKEND }} --name ${{ secrets.APP }} -p 8080:8080 --network=${{ secrets.DOCKER_NETWORK }} ${{ secrets.DOCKER_USER }}/${{ secrets.APP }}:latest
